import matplotlib.pyplot as plt
from matplotlib import style
import time

def create_acc_loss_graph(model_name):
    """
    Creates a graph showing the accuracies and losses over epochs.
    :param model_name: path to the csv file with the reported accuracies and losses (generated by ConvNet.reported_fit).
    """
    contents = open(model_name,"r").read().split('\n')

    times = []
    accuracies = []
    losses = []

    val_accs = []
    val_losses = []

    for c in contents:
        if model_name in c:
            name,timestamp,acc,loss,val_acc,val_loss = c.split(",")

            times.append(float(timestamp))
            accuracies.append(float(acc))
            losses.append(float(loss))
            val_accs.append(float(val_acc))
            val_losses.append(float(val_loss))

    fig = plt.figure()
    ax1 = plt.subplot2grid((2,1),(0,0))
    ax2 = plt.subplot2grid((2,1),(1,0),sharex=ax1)

    ax1.plot(times,accuracies,label="acc")
    ax1.plot(times,val_accs,label="val_acc")
    ax1.legend(loc=2)

    ax2.plot(times,losses,label="loss")
    ax2.plot(times,val_losses,label="val_loss")
    ax2.legend(loc=2)

    file_name = f"{time.time()}"
    fig.savefig("./Plots/" + file_name + ".pdf")
    plt.show()